/**
 * VCPdesktop - 内置喵·鱼箱互动挂件模块
 * 功能：鱼箱里有自由游动的鱼，箱顶趴着一只猫，支持喂食互动
 * 作者：Nova
 */

'use strict';

(function () {
    const { state, CONSTANTS, widget } = window.VCPDesktop;

    var FISH_TANK_HTML = [
        '<style>',
        '.ft-container { position: relative; width: 320px; height: 380px; user-select: none; }',
        '',
        '/* === 猫咪区域 === */',
        '.ft-cat-area { position: absolute; top: 0; left: 0; right: 0; height: 60px; z-index: 10; display: flex; justify-content: center; align-items: flex-end; pointer-events: none; }',
        '.ft-cat { font-size: 40px; line-height: 1; transform: translateY(8px); transition: transform 0.3s ease; cursor: pointer; pointer-events: auto; }',
        '.ft-cat.excited { animation: ft-cat-excited 0.4s ease 3; }',
        '.ft-cat.paw { animation: ft-cat-paw 0.6s ease; }',
        '@keyframes ft-cat-excited { 0%,100% { transform: translateY(8px) rotate(0deg); } 25% { transform: translateY(2px) rotate(-5deg); } 75% { transform: translateY(2px) rotate(5deg); } }',
        '@keyframes ft-cat-paw { 0% { transform: translateY(8px); } 50% { transform: translateY(18px) scale(1.1); } 100% { transform: translateY(8px); } }',
        '',
        '/* === 鱼箱主体 === */',
        '.ft-tank { position: absolute; top: 50px; left: 10px; right: 10px; bottom: 10px; background: linear-gradient(180deg, rgba(20,80,130,0.7) 0%, rgba(10,50,90,0.85) 60%, rgba(30,60,50,0.9) 100%); border-radius: 4px 4px 12px 12px; border: 2px solid rgba(120,200,255,0.3); overflow: hidden; cursor: crosshair; box-shadow: 0 4px 20px rgba(0,100,200,0.2), inset 0 0 40px rgba(0,150,255,0.08); }',
        '',
        '/* === 水面波纹 === */',
        '.ft-surface { position: absolute; top: 0; left: -10%; right: -10%; height: 6px; background: linear-gradient(90deg, transparent, rgba(150,220,255,0.4), rgba(100,200,255,0.2), rgba(150,220,255,0.4), transparent); animation: ft-wave 3s ease-in-out infinite; z-index: 5; }',
        '@keyframes ft-wave { 0%,100% { transform: translateX(-5%) scaleY(1); } 50% { transform: translateX(5%) scaleY(1.5); } }',
        '',
        '/* === 水草 === */',
        '.ft-seaweed { position: absolute; bottom: 0; width: 8px; border-radius: 4px 4px 0 0; transform-origin: bottom center; }',
        '.ft-sw1 { left: 15%; height: 60px; background: linear-gradient(to top, #2d6b3f, #4a9e5e); animation: ft-sway 4s ease-in-out infinite; }',
        '.ft-sw2 { left: 35%; height: 45px; background: linear-gradient(to top, #1e5c30, #3d8a4f); animation: ft-sway 3.5s ease-in-out infinite reverse; }',
        '.ft-sw3 { right: 20%; height: 55px; background: linear-gradient(to top, #2a6638, #52a862); animation: ft-sway 4.5s ease-in-out infinite 0.5s; }',
        '.ft-sw4 { right: 40%; height: 38px; background: linear-gradient(to top, #1a5028, #358545); animation: ft-sway 3s ease-in-out infinite 1s; }',
        '@keyframes ft-sway { 0%,100% { transform: rotate(-5deg); } 50% { transform: rotate(5deg); } }',
        '',
        '/* === 砂石底部 === */',
        '.ft-ground { position: absolute; bottom: 0; left: 0; right: 0; height: 20px; background: linear-gradient(to top, rgba(120,100,60,0.9), rgba(80,70,40,0.6), transparent); border-radius: 0 0 10px 10px; }',
        '',
        '/* === 气泡 === */',
        '.ft-bubble { position: absolute; border-radius: 50%; background: radial-gradient(circle at 30% 30%, rgba(200,240,255,0.6), rgba(100,180,230,0.2)); border: 1px solid rgba(180,220,255,0.3); animation: ft-rise linear forwards; pointer-events: none; }',
        '@keyframes ft-rise { 0% { opacity: 0.8; transform: translateX(0) scale(1); } 50% { opacity: 0.6; transform: translateX(8px) scale(1.1); } 100% { opacity: 0; transform: translateX(-4px) scale(0.8); top: -10px; } }',
        '',
        '/* === 鱼 === */',
        '.ft-fish { position: absolute; transition: none; z-index: 3; pointer-events: none; }',
        '.ft-fish-body { font-size: 24px; line-height: 1; transition: transform 0.2s ease; }',
        '.ft-fish.flip .ft-fish-body { transform: scaleX(-1); }',
        '',
        '/* === 鱼食 === */',
        '.ft-food { position: absolute; width: 4px; height: 4px; border-radius: 50%; background: radial-gradient(circle, #e8a030, #c07020); z-index: 4; pointer-events: none; animation: ft-food-fall linear forwards; box-shadow: 0 0 3px rgba(200,150,50,0.5); }',
        '@keyframes ft-food-fall { 0% { opacity: 1; } 100% { opacity: 0.6; } }',
        '',
        '/* === 控制栏 === */',
        '.ft-controls { position: absolute; bottom: 14px; left: 50%; transform: translateX(-50%); display: flex; gap: 6px; z-index: 8; }',
        '.ft-btn { padding: 4px 10px; border: none; background: rgba(255,255,255,0.12); color: rgba(255,255,255,0.8); border-radius: 12px; font-size: 11px; cursor: pointer; transition: all 0.15s; backdrop-filter: blur(4px); }',
        '.ft-btn:hover { background: rgba(255,255,255,0.22); color: #fff; transform: scale(1.05); }',
        '.ft-btn.active { background: rgba(100,200,255,0.25); color: rgba(100,220,255,0.95); }',
        '',
        '/* === 信息面板 === */',
        '.ft-info { position: absolute; top: 6px; right: 8px; font-size: 10px; color: rgba(180,220,255,0.6); z-index: 6; text-align: right; line-height: 1.5; }',
        '',
        '/* === 光影效果 === */',
        '.ft-light { position: absolute; top: 0; left: 0; right: 0; bottom: 0; background: radial-gradient(ellipse at 50% 0%, rgba(100,200,255,0.08) 0%, transparent 60%); pointer-events: none; z-index: 2; }',
        '</style>',
        '',
        '<div class="ft-container">',
        '    <div class="ft-cat-area"><span class="ft-cat" id="ft-cat" title="点我！喵~">🐱</span></div>',
        '    <div class="ft-tank" id="ft-tank">',
        '        <div class="ft-surface"></div>',
        '        <div class="ft-light"></div>',
        '        <div class="ft-seaweed ft-sw1"></div>',
        '        <div class="ft-seaweed ft-sw2"></div>',
        '        <div class="ft-seaweed ft-sw3"></div>',
        '        <div class="ft-seaweed ft-sw4"></div>',
        '        <div class="ft-ground"></div>',
        '        <div class="ft-info" id="ft-info">🐟 ×0</div>',
        '        <div class="ft-controls">',
        '            <button class="ft-btn" id="ft-feed" title="撒鱼食">🍞 喂食</button>',
        '            <button class="ft-btn" id="ft-add" title="加一条鱼">🐟 加鱼</button>',
        '            <button class="ft-btn" id="ft-bubble-btn" title="吹泡泡">🫧 泡泡</button>',
        '        </div>',
        '    </div>',
        '</div>',
        '',
        '<script>',
        '(function() {',
        '    var tank = document.getElementById("ft-tank");',
        '    var catEl = document.getElementById("ft-cat");',
        '    var infoEl = document.getElementById("ft-info");',
        '    var feedBtn = document.getElementById("ft-feed");',
        '    var addBtn = document.getElementById("ft-add");',
        '    var bubbleBtn = document.getElementById("ft-bubble-btn");',
        '',
        '    var fishes = [];',
        '    var foods = [];',
        '    var fishEmojis = ["🐟", "🐠", "🐡", "🦈", "🐙", "🦑", "🦐", "🐳"];',
        '    var fishId = 0;',
        '    var animFrame = null;',
        '    var feedCount = 0;',
        '',
        '    function rand(min, max) { return Math.random() * (max - min) + min; }',
        '',
        '    function getTankRect() {',
        '        return { w: tank.offsetWidth || 300, h: tank.offsetHeight || 310 };',
        '    }',
        '',
        '    // === 创建鱼 ===',
        '    function createFish(x, y) {',
        '        var r = getTankRect();',
        '        var fish = {',
        '            id: fishId++,',
        '            x: x !== undefined ? x : rand(30, r.w - 50),',
        '            y: y !== undefined ? y : rand(30, r.h - 60),',
        '            vx: rand(-1.2, 1.2),',
        '            vy: rand(-0.6, 0.6),',
        '            emoji: fishEmojis[Math.floor(rand(0, fishEmojis.length))],',
        '            size: rand(20, 32),',
        '            targetFood: null,',
        '            el: null',
        '        };',
        '        var el = document.createElement("div");',
        '        el.className = "ft-fish";',
        '        el.innerHTML = \'<span class="ft-fish-body" style="font-size:\' + fish.size + \'px">\' + fish.emoji + \'</span>\';',
        '        el.style.left = fish.x + "px";',
        '        el.style.top = fish.y + "px";',
        '        tank.appendChild(el);',
        '        fish.el = el;',
        '        fishes.push(fish);',
        '        updateInfo();',
        '        triggerCat("excited");',
        '        return fish;',
        '    }',
        '',
        '    // === 创建鱼食 ===',
        '    function createFood(x) {',
        '        var food = {',
        '            x: x,',
        '            y: 8,',
        '            vy: rand(0.3, 0.8),',
        '            eaten: false,',
        '            el: null',
        '        };',
        '        var el = document.createElement("div");',
        '        el.className = "ft-food";',
        '        el.style.left = food.x + "px";',
        '        el.style.top = food.y + "px";',
        '        tank.appendChild(el);',
        '        food.el = el;',
        '        foods.push(food);',
        '        return food;',
        '    }',
        '',
        '    // === 吹泡泡 ===',
        '    function createBubble(x, y) {',
        '        var r = getTankRect();',
        '        var bx = x !== undefined ? x : rand(20, r.w - 20);',
        '        var by = y !== undefined ? y : rand(r.h * 0.4, r.h * 0.8);',
        '        var size = rand(4, 12);',
        '        var el = document.createElement("div");',
        '        el.className = "ft-bubble";',
        '        el.style.left = bx + "px";',
        '        el.style.top = by + "px";',
        '        el.style.width = size + "px";',
        '        el.style.height = size + "px";',
        '        el.style.animationDuration = rand(2, 4) + "s";',
        '        tank.appendChild(el);',
        '        setTimeout(function() { if (el.parentNode) el.parentNode.removeChild(el); }, 4500);',
        '    }',
        '',
        '    // === 猫咪反应 ===',
        '    function triggerCat(type) {',
        '        catEl.classList.remove("excited", "paw");',
        '        void catEl.offsetWidth;',
        '        catEl.classList.add(type);',
        '        setTimeout(function() { catEl.classList.remove(type); }, 2000);',
        '    }',
        '',
        '    // === 更新信息 ===',
        '    function updateInfo() {',
        '        infoEl.innerHTML = "🐟 ×" + fishes.length + (feedCount > 0 ? "<br>🍞 ×" + feedCount : "");',
        '    }',
        '',
        '    // === 主动画循环 ===',
        '    function animate() {',
        '        var r = getTankRect();',
        '        var margin = 20;',
        '        var groundH = 30;',
        '',
        '        // 更新鱼食位置',
        '        for (var fi = foods.length - 1; fi >= 0; fi--) {',
        '            var food = foods[fi];',
        '            if (food.eaten) {',
        '                if (food.el && food.el.parentNode) food.el.parentNode.removeChild(food.el);',
        '                foods.splice(fi, 1);',
        '                continue;',
        '            }',
        '            food.y += food.vy;',
        '            if (food.y > r.h - groundH) {',
        '                food.y = r.h - groundH;',
        '                food.vy = 0;',
        '            }',
        '            food.el.style.top = food.y + "px";',
        '        }',
        '',
        '        // 更新鱼位置',
        '        for (var i = 0; i < fishes.length; i++) {',
        '            var fish = fishes[i];',
        '',
        '            // 寻找最近的食物',
        '            var nearestFood = null;',
        '            var nearestDist = Infinity;',
        '            for (var j = 0; j < foods.length; j++) {',
        '                if (foods[j].eaten) continue;',
        '                var dx = foods[j].x - fish.x;',
        '                var dy = foods[j].y - fish.y;',
        '                var dist = Math.sqrt(dx * dx + dy * dy);',
        '                if (dist < nearestDist) {',
        '                    nearestDist = dist;',
        '                    nearestFood = foods[j];',
        '                }',
        '            }',
        '',
        '            if (nearestFood && nearestDist < 150) {',
        '                // 游向食物',
        '                var fdx = nearestFood.x - fish.x;',
        '                var fdy = nearestFood.y - fish.y;',
        '                var fd = Math.sqrt(fdx * fdx + fdy * fdy) || 1;',
        '                fish.vx += (fdx / fd) * 0.15;',
        '                fish.vy += (fdy / fd) * 0.15;',
        '',
        '                // 吃到食物',
        '                if (nearestDist < 15) {',
        '                    nearestFood.eaten = true;',
        '                    feedCount++;',
        '                    updateInfo();',
        '                    triggerCat("paw");',
        '                    // 吃东西时吐泡泡',
        '                    createBubble(fish.x, fish.y);',
        '                }',
        '            } else {',
        '                // 自由游动：随机改变方向',
        '                fish.vx += rand(-0.08, 0.08);',
        '                fish.vy += rand(-0.05, 0.05);',
        '            }',
        '',
        '            // 速度限制',
        '            var speed = Math.sqrt(fish.vx * fish.vx + fish.vy * fish.vy);',
        '            var maxSpeed = nearestFood ? 2.0 : 1.2;',
        '            if (speed > maxSpeed) {',
        '                fish.vx = (fish.vx / speed) * maxSpeed;',
        '                fish.vy = (fish.vy / speed) * maxSpeed;',
        '            }',
        '',
        '            fish.x += fish.vx;',
        '            fish.y += fish.vy;',
        '',
        '            // 边界反弹',
        '            if (fish.x < margin) { fish.x = margin; fish.vx = Math.abs(fish.vx) * 0.8; }',
        '            if (fish.x > r.w - margin - 20) { fish.x = r.w - margin - 20; fish.vx = -Math.abs(fish.vx) * 0.8; }',
        '            if (fish.y < margin) { fish.y = margin; fish.vy = Math.abs(fish.vy) * 0.8; }',
        '            if (fish.y > r.h - groundH - 20) { fish.y = r.h - groundH - 20; fish.vy = -Math.abs(fish.vy) * 0.8; }',
        '',
        '            // 朝向',
        '            if (fish.vx > 0.1) fish.el.classList.remove("flip");',
        '            else if (fish.vx < -0.1) fish.el.classList.add("flip");',
        '',
        '            fish.el.style.left = fish.x + "px";',
        '            fish.el.style.top = fish.y + "px";',
        '        }',
        '',
        '        // 随机泡泡（低概率）',
        '        if (Math.random() < 0.008 && fishes.length > 0) {',
        '            var rf = fishes[Math.floor(rand(0, fishes.length))];',
        '            createBubble(rf.x + 10, rf.y);',
        '        }',
        '',
        '        animFrame = requestAnimationFrame(animate);',
        '    }',
        '',
        '    // === 点击鱼箱喂食 ===',
        '    tank.addEventListener("click", function(e) {',
        '        var rect = tank.getBoundingClientRect();',
        '        var x = e.clientX - rect.left;',
        '        var y = e.clientY - rect.top;',
        '        // 只在上半部分点击时撒食',
        '        if (y < rect.height * 0.3) {',
        '            for (var i = 0; i < 3; i++) {',
        '                createFood(x + rand(-15, 15));',
        '            }',
        '            triggerCat("excited");',
        '        }',
        '    });',
        '',
        '    // === 喂食按钮 ===',
        '    feedBtn.addEventListener("click", function(e) {',
        '        e.stopPropagation();',
        '        var r = getTankRect();',
        '        for (var i = 0; i < 5; i++) {',
        '            createFood(rand(30, r.w - 30));',
        '        }',
        '        triggerCat("excited");',
        '    });',
        '',
        '    // === 加鱼按钮 ===',
        '    addBtn.addEventListener("click", function(e) {',
        '        e.stopPropagation();',
        '        if (fishes.length < 15) {',
        '            createFish();',
        '        }',
        '    });',
        '',
        '    // === 泡泡按钮 ===',
        '    bubbleBtn.addEventListener("click", function(e) {',
        '        e.stopPropagation();',
        '        for (var i = 0; i < 8; i++) {',
        '            setTimeout(function() { createBubble(); }, i * 150);',
        '        }',
        '    });',
        '',
        '    // === 点击猫咪 ===',
        '    catEl.addEventListener("click", function() {',
        '        triggerCat("excited");',
        '        // 猫拍水面，惊扰鱼群',
        '        for (var i = 0; i < fishes.length; i++) {',
        '            fishes[i].vx += rand(-3, 3);',
        '            fishes[i].vy += rand(0.5, 2);',
        '        }',
        '        for (var j = 0; j < 5; j++) {',
        '            createBubble(rand(40, getTankRect().w - 40), 10);',
        '        }',
        '    });',
        '',
        '    // === 初始化：放3条鱼 ===',
        '    createFish();',
        '    createFish();',
        '    createFish();',
        '',
        '    // 启动动画',
        '    animate();',
        '})();',
        '<\\/script>'
    ].join('\n');

    /**
     * 生成鱼箱挂件
     */
    async function spawnFishTankWidget() {
        var widgetId = 'builtin-fishtank';

        if (state.widgets.has(widgetId)) return;

        var widgetData = widget.create(widgetId, {
            x: 700,
            y: CONSTANTS.TITLE_BAR_HEIGHT + 20,
            width: 340,
            height: 400,
        });

        widgetData.contentBuffer = FISH_TANK_HTML;
        widgetData.contentContainer.innerHTML = FISH_TANK_HTML;
        widget.processInlineStyles(widgetData);
        widgetData.isConstructing = false;
        widgetData.element.classList.remove('constructing');
        widget.autoResize(widgetData);

        setTimeout(function () {
            widget.processInlineScripts(widgetData);
        }, 100);

        console.log('[VCPdesktop] Fish tank widget spawned. 🐟');
    }

    // ============================================================
    // 导出
    // ============================================================
    window.VCPDesktop = window.VCPDesktop || {};
    window.VCPDesktop.builtinFishTank = {
        spawn: spawnFishTankWidget,
    };

})();